Trait {
	#name : 'ProliExTestProperOperationService',
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : 'PrototypeLink-Example-services',
	#package : 'PrototypeLink-Example',
	#tag : 'services'
}

{ #category : 'as yet unclassified' }
ProliExTestProperOperationService >> sensorOfCrossRoad [

	
]

{ #category : 'as yet unclassified' }
ProliExTestProperOperationService >> sensorOfTrack: aNumber [

	
]

{ #category : 'as yet unclassified' }
ProliExTestProperOperationService >> sensorOfVehiculeOnTrack [

	
]
