Trait {
	#name : 'ProliExImplementArrivalProcedureService',
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : 'PrototypeLink-Example-services',
	#package : 'PrototypeLink-Example',
	#tag : 'services'
}

{ #category : 'as yet unclassified' }
ProliExImplementArrivalProcedureService >> trainArrivalAuthorization [
]

{ #category : 'as yet unclassified' }
ProliExImplementArrivalProcedureService >> trainDelayOnArrival [
]
