Trait {
	#name : 'ProliExControlPowerSupplyToTrainsService',
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : 'PrototypeLink-Example-services',
	#package : 'PrototypeLink-Example',
	#tag : 'services'
}

{ #category : 'as yet unclassified' }
ProliExControlPowerSupplyToTrainsService >> emergencyTrainStop [
]

{ #category : 'as yet unclassified' }
ProliExControlPowerSupplyToTrainsService >> trainTrafficRelease [

	
]
