Trait {
	#name : 'ProliExControlMovmentsOnTrack',
	#traits : 'MolComponentEvents',
	#classTraits : 'MolComponentEvents classTrait',
	#category : 'PrototypeLink-Example-events',
	#package : 'PrototypeLink-Example',
	#tag : 'events'
}

{ #category : 'as yet unclassified' }
ProliExControlMovmentsOnTrack >> arrivingTrain: aTrain [

	
]

{ #category : 'as yet unclassified' }
ProliExControlMovmentsOnTrack >> departingTrain: aTrain [

	
]

{ #category : 'as yet unclassified' }
ProliExControlMovmentsOnTrack >> trainPassingTheLevelCrossing [

	
]

{ #category : 'as yet unclassified' }
ProliExControlMovmentsOnTrack >> vehiculeEnteredTheCrossing [
]

{ #category : 'as yet unclassified' }
ProliExControlMovmentsOnTrack >> vehiculeLeavedTheCrossing [

	
]
