Trait {
	#name : 'ProliExImplementDepartureProcedureService',
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : 'PrototypeLink-Example-services',
	#package : 'PrototypeLink-Example',
	#tag : 'services'
}

{ #category : 'as yet unclassified' }
ProliExImplementDepartureProcedureService >> trainDelayOnDeparture [

	
]

{ #category : 'as yet unclassified' }
ProliExImplementDepartureProcedureService >> trainDepartureAuthorization [
]
