Trait {
	#name : 'ProliExTestProperOperationEvent',
	#traits : 'MolComponentEvents',
	#classTraits : 'MolComponentEvents classTrait',
	#category : 'PrototypeLink-Example-events',
	#package : 'PrototypeLink-Example',
	#tag : 'events'
}

{ #category : 'as yet unclassified' }
ProliExTestProperOperationEvent >> statusOfCrossRoad: aStatus [

	
]

{ #category : 'as yet unclassified' }
ProliExTestProperOperationEvent >> statusOfTrack: aStatus number: aNumber [

	
]

{ #category : 'as yet unclassified' }
ProliExTestProperOperationEvent >> statusOfVehiculeOnTrack: aStatus [

	
]
